import { DEVICE_PRESET_IDS } from "@/data/devices/registry";
import type { TemplateDefinition } from "../schema";
import { baseRecipeDesign } from "./common";

type TemplateSeed = Pick<TemplateDefinition, "id" | "name" | "description"> & {
  tags: string[];
  subjects: string[];
  design: Partial<TemplateDefinition["recipe"]["design"]>;
};

function makePhoneTemplate({
  id,
  name,
  description,
  tags,
  subjects,
  design,
}: TemplateSeed): TemplateDefinition {
  return {
    schemaVersion: 1,
    revision: 1,
    id,
    name,
    description,
    device: { category: "phone", presetId: DEVICE_PRESET_IDS.android },
    presentation: { tags, subjects },
    recipe: {
      design: {
        ...baseRecipeDesign,
        ...design,
        layoutStyles: {
          ...baseRecipeDesign.layoutStyles,
          ...design.layoutStyles,
        },
        subjectColors: {
          mode: "automatic",
          singleColor: null,
          bySubjectId: {},
        },
      },
      showTitle: true,
      schedulePosition: { x: 0.5, y: 0.54 },
      scheduleSize: {
        widthRatio: 0.9,
        heightRatio: 0.56,
        lockAspectRatio: false,
      },
      stickers: [],
    },
  };
}

export const BETA_TEMPLATES: readonly TemplateDefinition[] = [
  makePhoneTemplate({
    id: "azul-scholar",
    name: "Azul Scholar",
    description: "A crisp blue-and-white academic look inspired by AdZU.",
    tags: ["AdZU-inspired", "Academic"],
    subjects: ["ALGORITHMS", "HCI", "SOFTENG", "INFOSEC", "WEBPROG", "OPSYS"],
    design: {
      layoutId: "grid",
      layoutStyles: { ...baseRecipeDesign.layoutStyles, grid: "grid-outline" },
      themeId: "adzu-classic",
      typography: { presetId: "cormorant-source-sans" },
      density: "comfortable",
      visibleFields: {
        time: false,
        room: true,
        professor: false,
        section: false,
      },
      background: {
        mode: "gradient",
        gradient: {
          type: "linear",
          color1: "#F7FAFF",
          color2: "#DCEBFA",
          direction: 135,
          center: { x: 0.5, y: 0.5 },
        },
      },
    },
  }),
  makePhoneTemplate({
    id: "crimson-focus",
    name: "Crimson Focus",
    description: "Confident crimson and white, inspired by WMSU school spirit.",
    tags: ["WMSU-inspired", "Bold"],
    subjects: ["NURANP", "NURBIO", "NURMIC", "NCM 104j", "NCM 105j", "ETHICS"],
    design: {
      layoutId: "cards",
      layoutStyles: { ...baseRecipeDesign.layoutStyles, cards: "cards-bold" },
      themeId: "wmsu-crimson",
      typography: { presetId: "league-spartan-inter" },
      density: "comfortable",
      visibleFields: {
        time: true,
        room: true,
        professor: false,
        section: false,
      },
      background: {
        mode: "gradient",
        gradient: {
          type: "linear",
          color1: "#FFF8F6",
          color2: "#F4DDE2",
          direction: 180,
          center: { x: 0.5, y: 0.5 },
        },
      },
    },
  }),
  makePhoneTemplate({
    id: "moss-and-ivory",
    name: "Moss & Ivory",
    description:
      "A calm moss-green study palette inspired by Universidad de Zamboanga.",
    tags: ["UZ-inspired", "Calm"],
    subjects: [
      "BUSFIN",
      "ENTRE 1",
      "TAX 01",
      "LAW 01",
      "MANACC 01",
      "MRKTGM 201",
    ],
    design: {
      layoutId: "planner",
      layoutStyles: {
        ...baseRecipeDesign.layoutStyles,
        planner: "planner-editorial",
      },
      themeId: "uz-moss",
      typography: { presetId: "playfair-inter" },
      density: "comfortable",
      visibleFields: {
        time: true,
        room: true,
        professor: false,
        section: false,
      },
      background: {
        mode: "pattern",
        pattern: {
          type: "dots",
          backgroundColor: "#F7F5E9",
          color: "#596B43",
          size: 0.004,
          spacing: 0.075,
          opacity: 0.1,
          offset: true,
        },
      },
    },
  }),
  makePhoneTemplate({
    id: "maroon-workshop",
    name: "Maroon Workshop",
    description: "Practical maroon and gold with a polished polytechnic feel.",
    tags: ["ZPPSU-inspired", "Structured"],
    subjects: ["CE.311", "CE.312", "CE.315", "ENG.311", "CE.321", "CE.323"],
    design: {
      layoutId: "grid",
      layoutStyles: { ...baseRecipeDesign.layoutStyles, grid: "grid-filled" },
      themeId: "zppsu-maroon-gold",
      typography: { presetId: "outfit-dm-sans" },
      density: "comfortable",
      visibleFields: {
        time: false,
        room: true,
        professor: false,
        section: false,
      },
      background: {
        mode: "gradient",
        gradient: {
          type: "linear",
          color1: "#FFF9F0",
          color2: "#F0DFC1",
          direction: 135,
          center: { x: 0.5, y: 0.5 },
        },
      },
    },
  }),
  makePhoneTemplate({
    id: "sakura-notes",
    name: "Sakura Notes",
    description: "Soft blush layers with an elegant handwritten title.",
    tags: ["Pastel", "Elegant"],
    subjects: [
      "PSYC 03",
      "PSYC 04",
      "PSYC 08n",
      "PSYC 10",
      "PSYC 14",
      "PSYC SCI1",
    ],
    design: {
      layoutId: "planner",
      layoutStyles: {
        ...baseRecipeDesign.layoutStyles,
        planner: "planner-soft",
      },
      themeId: "pink-diary",
      typography: { presetId: "allura-manrope" },
      density: "comfortable",
      visibleFields: {
        time: true,
        room: true,
        professor: false,
        section: false,
      },
      background: {
        mode: "gradient",
        gradient: {
          type: "linear",
          color1: "#FFF8FA",
          color2: "#F8DDE7",
          direction: 180,
          center: { x: 0.5, y: 0.5 },
        },
      },
    },
  }),
  makePhoneTemplate({
    id: "midnight-cobalt",
    name: "Midnight Cobalt",
    description: "A deep-blue focus mode with cool, luminous accents.",
    tags: ["Dark", "Focused"],
    subjects: ["AI", "OPSYS", "DATAMIN", "INFOSEC", "THESIS1", "PROGLANG"],
    design: {
      layoutId: "grid",
      layoutStyles: { ...baseRecipeDesign.layoutStyles, grid: "grid-outline" },
      themeId: "midnight",
      typography: { presetId: "outfit-dm-sans" },
      density: "compact",
      visibleFields: {
        time: false,
        room: true,
        professor: false,
        section: false,
      },
      background: {
        mode: "gradient",
        gradient: {
          type: "linear",
          color1: "#07152D",
          color2: "#173A67",
          direction: 135,
          center: { x: 0.5, y: 0.5 },
        },
      },
    },
  }),
  makePhoneTemplate({
    id: "citrus-pop",
    name: "Citrus Pop",
    description: "Bright tangerine and apricot for an energetic weekly view.",
    tags: ["Colorful", "Playful"],
    subjects: [
      "JOURNP-1",
      "CREWRI",
      "DIGPUB",
      "PHOTOJOURN",
      "SOCMED",
      "FILMPROD",
    ],
    design: {
      layoutId: "cards",
      layoutStyles: { ...baseRecipeDesign.layoutStyles, cards: "cards-soft" },
      themeId: "custom",
      customPalette: {
        basedOnPaletteId: "siteao-orange",
        canvas: "#FFF9EF",
        primary: "#38251B",
        secondary: "#735E50",
        accent: "#E6693E",
        surface: "#FFFDF7",
        border: "#F0D3BC",
      },
      typography: { presetId: "poppins-inter" },
      density: "comfortable",
      visibleFields: {
        time: true,
        room: false,
        professor: false,
        section: false,
      },
      background: {
        mode: "pattern",
        pattern: {
          type: "checker",
          backgroundColor: "#FFF9EF",
          color: "#F6B84A",
          cellSize: 0.05,
          opacity: 0.08,
        },
      },
    },
  }),
  makePhoneTemplate({
    id: "warm-paper",
    name: "Warm Paper",
    description: "Terracotta, sage, and ochre on a warm editorial canvas.",
    tags: ["Editorial", "Warm"],
    subjects: ["PHIHUM", "LOGIC", "ETHICS", "RIZAL", "CONWOR", "ACADWRI"],
    design: {
      layoutId: "minimal",
      layoutStyles: {
        ...baseRecipeDesign.layoutStyles,
        minimal: "minimal-editorial",
      },
      themeId: "custom",
      customPalette: {
        basedOnPaletteId: "matcha-study",
        canvas: "#F4EFE6",
        primary: "#342D27",
        secondary: "#71675D",
        accent: "#A5533D",
        surface: "#FBF8F2",
        border: "#D9CFC0",
      },
      typography: { presetId: "cormorant-source-sans" },
      density: "detailed",
      visibleFields: {
        time: true,
        room: true,
        professor: true,
        section: false,
      },
      background: {
        mode: "solid",
        solid: { color: "#F4EFE6" },
      },
    },
  }),
  makePhoneTemplate({
    id: "aurora-glass",
    name: "Aurora Glass",
    description:
      "An atmospheric teal-to-indigo gradient with glassy schedule cards.",
    tags: ["Gradient", "Modern"],
    subjects: [
      "AUTOMATA",
      "COMARCH",
      "DATAMAN",
      "SERSCRIPT",
      "COGNATE2",
      "WEBSYSTECH",
    ],
    design: {
      layoutId: "cards",
      layoutStyles: { ...baseRecipeDesign.layoutStyles, cards: "cards-glass" },
      themeId: "custom",
      customPalette: {
        basedOnPaletteId: "midnight",
        canvas: "#071A2B",
        primary: "#F4FBFF",
        secondary: "#B5CFD8",
        accent: "#57D8D0",
        surface: "#102B45",
        border: "#2A5870",
      },
      typography: { presetId: "poppins-inter" },
      density: "comfortable",
      visibleFields: {
        time: true,
        room: true,
        professor: false,
        section: false,
      },
      background: {
        mode: "gradient",
        gradient: {
          type: "linear",
          color1: "#071A2B",
          color2: "#31528C",
          direction: 135,
          center: { x: 0.5, y: 0.5 },
        },
      },
    },
  }),
  makePhoneTemplate({
    id: "lilac-bloom",
    name: "Lilac Bloom",
    description: "Layered lavender tones with a soft, contemporary rhythm.",
    tags: ["Pastel", "Soft"],
    subjects: ["ACADWRI", "LITMIN", "LIVIT", "CREWRI", "THEATER", "COMTHEO"],
    design: {
      layoutId: "cards",
      layoutStyles: { ...baseRecipeDesign.layoutStyles, cards: "cards-soft" },
      themeId: "girlfriends-choice",
      typography: { presetId: "quicksand-dm-sans" },
      density: "comfortable",
      visibleFields: {
        time: true,
        room: false,
        professor: false,
        section: false,
      },
      background: {
        mode: "gradient",
        gradient: {
          type: "linear",
          color1: "#F8F4FB",
          color2: "#DDD0EC",
          direction: 180,
          center: { x: 0.5, y: 0.5 },
        },
      },
    },
  }),
  makePhoneTemplate({
    id: "golden-hour",
    name: "Golden Hour",
    description: "Warm sunflower layers with a confident graphic structure.",
    tags: ["Bright", "Graphic"],
    subjects: [
      "ECON 201",
      "BUSMAN 209",
      "ENTRE 2",
      "BUSANA 3",
      "MRKTGM 202",
      "TAX 02",
    ],
    design: {
      layoutId: "grid",
      layoutStyles: { ...baseRecipeDesign.layoutStyles, grid: "grid-filled" },
      themeId: "aao-yellow",
      typography: { presetId: "league-spartan-inter" },
      density: "comfortable",
      visibleFields: {
        time: false,
        room: true,
        professor: false,
        section: false,
      },
      background: {
        mode: "pattern",
        pattern: {
          type: "diagonal",
          backgroundColor: "#FFF9E8",
          color: "#D9A31A",
          stripeWidth: 0.008,
          spacing: 0.075,
          angle: 135,
          opacity: 0.1,
        },
      },
    },
  }),
  makePhoneTemplate({
    id: "ink-grid",
    name: "Ink Grid",
    description: "A precise monochrome system with restrained cobalt accents.",
    tags: ["Minimal", "Monochrome"],
    subjects: ["CE.411", "CE.412", "CE.414", "CE.417", "CE.421", "CE.423"],
    design: {
      layoutId: "minimal",
      layoutStyles: {
        ...baseRecipeDesign.layoutStyles,
        minimal: "minimal-bold",
      },
      themeId: "custom",
      customPalette: {
        basedOnPaletteId: "clean-slate",
        canvas: "#F5F7FA",
        primary: "#161B22",
        secondary: "#596273",
        accent: "#315FAD",
        surface: "#FFFFFF",
        border: "#CBD2DC",
      },
      typography: { presetId: "outfit-dm-sans" },
      density: "detailed",
      visibleFields: {
        time: true,
        room: true,
        professor: true,
        section: false,
      },
      background: {
        mode: "pattern",
        pattern: {
          type: "grid",
          backgroundColor: "#F5F7FA",
          color: "#315FAD",
          spacing: 0.06,
          lineWeight: 0.001,
          opacity: 0.07,
        },
      },
    },
  }),
];
